// <auto-generated />
using System;
using FNS.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NodaTime;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FNS.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FNS.Domain.Models.Products.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Instant>("AddedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("Price")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric")
                        .HasDefaultValue(0m);

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("SubCategoryId")
                        .HasColumnType("uuid");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid");

                    b.HasKey("Id");

                    b.HasIndex("SubCategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            AddedAt = NodaTime.Instant.FromUnixTimeTicks(16608536934491412L),
                            Description = "Labore iusto quidem non eos tempora impedit qui minima. Quis autem nihil suscipit dolores fugiat in omnis. Ut vero quisquam omnis culpa. Rem explicabo fuga. Perspiciatis esse facere incidunt beatae inventore qui. Enim minima alias doloribus possimus aspernatur dolorum omnis porro officia.\n\nMinima qui eum aut velit voluptatem cum delectus voluptatem. Adipisci sit vel quia aliquid. Ullam voluptas aperiam est sapiente. At consequatur vel. Quia nihil aut. Sed tenetur asperiores quibusdam quia.\n\nCorporis nostrum in nihil. Nostrum non qui in quaerat animi. Qui et omnis nemo fugiat. Et sit porro alias veniam magnam.\n\nPorro eligendi eius quidem quas eos impedit quis. Laudantium rerum eligendi dolorum soluta officiis commodi. Optio dolorum aliquam dolores. Et aliquid est labore. In placeat soluta soluta cum a.\n\nCorporis ipsum sint culpa velit iusto reiciendis. Id occaecati quas in. Aut cum mollitia id quasi magnam adipisci.",
                            Name = "AMD Ryzen 5 3600 OEM",
                            Price = 12599m,
                            ProductCode = "1372637",
                            SubCategoryId = new Guid("00000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            AddedAt = NodaTime.Instant.FromUnixTimeTicks(16608536934561874L),
                            Description = "Veritatis aut iusto quibusdam. Dolore consequatur debitis. Explicabo et sed. Labore enim non voluptas itaque praesentium facere pariatur. Qui nemo iste omnis. Optio et iusto non.\n\nPariatur nobis vel molestias quod aspernatur molestiae voluptas nesciunt quo. Vitae inventore id sit est. Officiis fugit explicabo quia ea at doloribus. Quae iusto totam.\n\nNobis tempora totam sed. Est qui natus mollitia aut qui voluptas. Et aut ut amet expedita esse magnam aut. Quod corporis adipisci doloremque sed. Veniam eaque qui illum.\n\nConsequatur aut laboriosam magni ut. Maiores quia quia fugit. Qui et voluptatem perferendis dolor qui doloremque cum. Veritatis voluptatem placeat accusantium dolorem error nisi soluta non non. Ex corrupti eaque.\n\nAut delectus aut et aut qui praesentium ut. Accusamus incidunt et qui in quo aliquam ad quod. Aut nihil aut qui quaerat incidunt exercitationem qui.",
                            Name = "AMD Ryzen 5 3600 BOX",
                            Price = 12899m,
                            ProductCode = "5059834",
                            SubCategoryId = new Guid("00000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            AddedAt = NodaTime.Instant.FromUnixTimeTicks(16608536934573251L),
                            Description = "Consequatur in quidem sequi et excepturi. Nostrum sit deleniti cumque. Et sunt expedita eius dolores occaecati autem perferendis quo non.\n\nReprehenderit nihil quos et qui aut maiores facilis reiciendis consequatur. Quia deserunt itaque ipsam. Illo excepturi eius aut libero officiis impedit explicabo perspiciatis est. Ratione possimus consequuntur cumque.\n\nEveniet vero pariatur nam omnis corporis explicabo culpa. Rem ex quod tempore voluptate porro. Et voluptatibus ratione.\n\nDignissimos aperiam aut. Numquam quaerat nulla. Aut ea voluptatum veritatis omnis vel repellat. Qui et autem nam voluptatem. Voluptatem et maiores omnis in.\n\nAssumenda molestias nihil dolores optio unde illum sequi. Ratione ea sint quia repellat. Similique veritatis esse porro placeat expedita sed magnam pariatur deleniti.",
                            Name = "AMD Ryzen 5 PRO 4650G OEM",
                            Price = 12599m,
                            ProductCode = "1689358",
                            SubCategoryId = new Guid("00000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000004"),
                            AddedAt = NodaTime.Instant.FromUnixTimeTicks(16608536934584475L),
                            Description = "Dignissimos sed beatae aspernatur enim enim aliquid ut saepe. Deleniti reiciendis nam omnis unde velit voluptas eligendi. Sit harum quae omnis sunt sit. Eveniet at magnam cupiditate consequatur necessitatibus velit.\n\nAliquid voluptates a sint omnis. Sit commodi sapiente quia voluptatibus. Autem natus neque reiciendis vel in ut.\n\nIn qui cum. Labore corporis rerum. Nam odit enim recusandae doloribus nulla eum.\n\nAsperiores modi voluptatem non. Alias qui similique nihil aut ut et. In eaque est quia dicta blanditiis. Perspiciatis voluptatem eligendi consequatur qui. Voluptate aspernatur quia.\n\nTempora consequuntur perspiciatis voluptatibus natus iste. Saepe doloremque recusandae aut iusto. Possimus est rerum aperiam. Natus occaecati veniam repellat dolore quia sed. Eos atque pariatur aut.",
                            Name = "AMD Ryzen 5 5600G OEM",
                            Price = 14899m,
                            ProductCode = "4819672",
                            SubCategoryId = new Guid("00000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000005"),
                            AddedAt = NodaTime.Instant.FromUnixTimeTicks(16608536934595627L),
                            Description = "Perspiciatis ea exercitationem soluta sapiente modi quasi soluta omnis. Perferendis itaque ut vitae dignissimos ad rerum nesciunt aut. Ea iure rerum rerum laboriosam perferendis consequuntur modi dicta.\n\nDolore quod consectetur. Et alias mollitia porro necessitatibus. Odit deleniti veniam fugiat.\n\nOfficia laborum aspernatur magni itaque. Eum reiciendis illum voluptate reiciendis iusto. Provident laudantium ut velit quos doloribus veniam harum cum sint. Ullam rerum dolores rerum itaque ipsam amet sit. Qui aspernatur culpa molestiae autem at commodi itaque quia accusamus.\n\nOccaecati asperiores pariatur vitae rem eos dignissimos enim laboriosam. Nisi aut dolores impedit. Pariatur libero quia dolores omnis in. Aliquid et et debitis sunt aut quaerat.\n\nEt magni sed. Optio culpa voluptas sit. Est officia quo reiciendis rerum fugit aut nemo dignissimos eveniet. Laboriosam nihil molestiae fuga. Harum suscipit ab.",
                            Name = "AMD Ryzen 5 5600X OEM",
                            Price = 16199m,
                            ProductCode = "4721161",
                            SubCategoryId = new Guid("00000000-0000-0000-0000-000000000001")
                        });
                });

            modelBuilder.Entity("FNS.Domain.Models.Products.SubCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Instant>("AddedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid");

                    b.HasKey("Id");

                    b.ToTable("SubCategories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            AddedAt = NodaTime.Instant.FromUnixTimeTicks(0L),
                            Name = "Процессоры"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            AddedAt = NodaTime.Instant.FromUnixTimeTicks(0L),
                            Name = "Материские платы"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            AddedAt = NodaTime.Instant.FromUnixTimeTicks(0L),
                            Name = "Видеокарты"
                        });
                });

            modelBuilder.Entity("FNS.Domain.Models.Products.Product", b =>
                {
                    b.HasOne("FNS.Domain.Models.Products.SubCategory", "SubCategory")
                        .WithMany()
                        .HasForeignKey("SubCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubCategory");
                });
#pragma warning restore 612, 618
        }
    }
}
